apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metric-operator
  template:
    metadata:
      labels:
        name: metric-operator
    spec:
      serviceAccountName: metric-operator
      containers:
        - name: metric-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - metric-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "metric-operator"
